### ISSUE TITLE
views interface

### ISSUE THREAD

**Issue by mortendk** [thememachine/eleven#17]
# Where

http://drupal8.dev/admin/structure/views/view/content
 --- 

# todo:
-[ ] links.html.twig do some crazy stuff on contextual links 
- [ ] something from component/navigation is messing live previews and contectual up
- [ ]  contextual links from FEAT overwrites views ui ...'eleven/elevenfeat/templates/feat/contextual/_contextual.css'
- [ ] "add new" needs an update  to  
- [ ] input submit wrapper markup is making noise .... need to remove the wrapper or fix 'drupal8/core/modules/views_ui/js/views-admin.js'

--- 
# screenshots
![image](https://cloud.githubusercontent.com/assets/65756/24147260/af998cc2-0e39-11e7-8c2d-54b114a9b966.png)
